# Preface {.unnumbered}

This book was largely adapted from the public domain resource *Online Statistics Education: A Multimedia Course of Study* (<http://onlinestatbook.com/> Project Leader: David M. Lane, Rice University). A huge thanks to David Lane and his colleagues at Rice University for their creation of this wonderful resource. I use footnotes throughout to indicate precisely where the various sections of each chapter came from. Chapters 11-13 (and section 4.4) were written by me (Nathan).

This book is meant to be a free resource and is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1). You're welcome to share or adapt it, so long as you provide attribution to any work of mine that you use.

There are still formatting inconsistencies, and this is ever a work in progress. If you find errors, feel free to reach out (find updated contact info here: <https://nathanfavero.com>) so I can correct them for the next version I publish.

## What's Unique About This Text?

1.  It is a true introduction, not assuming any prior training in statistics.

2.  I try to minimize use of math (beyond the very elementary), instead focusing on conceptual description and interpretation.

3.  I introduce regression very early on (Ch. 3) so that students (especially PhD students) can quickly get started on their term papers and better understand any quantitative articles they're reading. The treatment of regression is further built out in the final chapters (11-13). Regression is, after all, the workhorse of applied statistics for the social sciences.

4.  I skip a traditional treatment of probability theory because I don't find traditional treatments to be very useful for students interested in applied statistics. Instead, I've written a chapter (11) on the logic and practice of building models that account for uncertainty.

5.  There is a bit of Stata code in the final chapter, but otherwise all examples are presented apart from any statistical software package.

## Past Versions

This version (1.3) was updated July 18, 2024. PDFs of past versions are available at <https://minusthemath.com>.

-   Version 1.3 updates: Added appendix (Ch. 3) on multiple regression and new section (4.4) on interpreting confidence intervals. Various formatting updates. Notation is updated in line with conventions: regression parameters are redone, and $\bar{X}$ is now used for sample mean and $n$ for sample size.

-   Version 1.2 updates: The discussion of transforming variables now appears in Ch. 2 (rather than Ch. 3).
